Fix: task_struct backwards-compatibility with kernel versions < 5.14
The state field in task_struct has been renamed to __state in kernel version 5.14.

Due to this change, xcapture-bpf.c fails with the following error on kernel versions < 5.14:
/virtual/main.c:178:29: error: no member named '__state' in 'struct task_struct'; did you mean 'state'?

This fix adds a bunch of macros to make xcapture-bpf.c backwards compatible with kernel versions < 5.14.

Example:

#if LINUX_VERSION_MAJOR >= 5 && LINUX_VERSION_PATCHLEVEL >= 14
        t->state = curtask->__state;
#else
        t->state = curtask->state;
#endif