Fix: task_struct backwards-compatibility with kernel versions < 5.14 (2)
The state field in task_struct has been renamed to __state in kernel version 5.14.

Due to this change, xcapture-bpf.c fails with the following error on kernel versions < 5.14:
/virtual/main.c:178:29: error: no member named '__state' in 'struct task_struct'; did you mean 'state'?

The state field rename has been backported to the RHEL8 4.18 kernels as well, but the fix in
#53 / 55f1e30 did not consider this. Therefore, this fix now also includes a macro that checks
for RHEL8 like so:

#if LINUX_VERSION_CODE >= KERNEL_VERSION(5, 14, 0) || RHEL_MAJOR >= 8
#define STATE_FIELD __state
#else
#define STATE_FIELD state
#endif
...
t->state = curtask->STATE_FIELD;